version: 2.1

orbs:
  mac: circleci/macos@2.3.0


jobs:
  mac-os:
    parameters:
      version:
        default: "14.1.0"
        type: string
    macos:
      xcode: << parameters.version >>
    resource_class: macos.m1.large.gen1
    parallelism: 60
    steps:
      - checkout
      - run: system_profiler SPDisplaysDataType
      - run:
          name: Check Metal device
          command: swift check_metal_device.swift

workflows:
  workflow1:
    jobs:
      - mac-os:
          matrix:
            parameters:
              version: ["14.1.0","14.2.0"]
 
